"""
Django settings for Forneria project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# estamos lo sacamos del pdf del profesor
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
LOGIN_URL = 'login'



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: SECRET_KEY desde variable de entorno (con default para desarrollo local)
# En producción, crear archivo .env con SECRET_KEY generado aleatoriamente
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-1_d+6q7z_jo1jhcm^gqi!qyij)n@5tlm5xemhc8b2eqvco9ya$'
)

# SECURITY: DEBUG desde variable de entorno (True para desarrollo local, False para producción)
# En producción, crear archivo .env con DEBUG=False
DEBUG = config('DEBUG', default=True, cast=bool)

# ALLOWED_HOSTS desde variable de entorno (con defaults para desarrollo local)
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,52.200.181.180',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# CSRF_TRUSTED_ORIGINS desde variable de entorno (con defaults para desarrollo local)
# En producción, usar HTTPS: CSRF_TRUSTED_ORIGINS=https://tudominio.com
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost,http://127.0.0.1,http://52.200.181.180',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/accounts/login/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rrhh',
    'ventas',
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ventas.middleware.RolMiddleware',  # Middleware para roles (RF-S1)
]

ROOT_URLCONF = 'Forneria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Forneria.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SECURITY: Credenciales de BD desde variables de entorno (con defaults para desarrollo local)
# En producción, crear archivo .env con valores reales
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='forneria'),
        'USER': config('DB_USER', default='forneria_user'),
        'PASSWORD': config('DB_PASSWORD', default='Ventana$123'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# LOGGING - CONFIGURACIÓN DE REGISTRO
# ============================================================

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO' if DEBUG else 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ventas': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================================
# CONFIGURACIONES ADICIONALES DE SEGURIDAD (Solo en producción)
# ============================================================

# Estas configuraciones solo se aplican cuando DEBUG=False
if not DEBUG:
    SESSION_COOKIE_SECURE = True  # Solo enviar cookies por HTTPS
    CSRF_COOKIE_SECURE = True     # Solo enviar CSRF por HTTPS
    SECURE_SSL_REDIRECT = True    # Redirigir HTTP a HTTPS
    SECURE_HSTS_SECONDS = 31536000  # HSTS (1 año)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# ============================================================
# CONFIGURACIÓN DE EMAIL
# ============================================================
# Para desarrollo: usar consola (los emails se imprimen en la terminal)
# Para producción: configurar SMTP real en variables de entorno

# Backend de email
# Opciones:
# - 'django.core.mail.backends.console.EmailBackend' (desarrollo - imprime en consola)
# - 'django.core.mail.backends.smtp.EmailBackend' (producción - envía emails reales)
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)

# Configuración SMTP (solo necesario si EMAIL_BACKEND es smtp)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Email desde el cual se envían los correos
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@forneria.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # Para errores del servidor

# URL base del sitio (para enlaces en emails, etc.)
# En desarrollo: dejar vacío o usar http://localhost:8000
# En producción: usar https://tudominio.com o http://tu-ip-elastica
# Si está vacío, Django usará request.build_absolute_uri() automáticamente
SITE_URL = config('SITE_URL', default='http://35.172.127.25')

# Tiempo de expiración del token de recuperación (en horas)
PASSWORD_RESET_TIMEOUT = 24  # 24 horas